Migrated to NULL SAFETY
scitbiz/flutter_pokedex pull request #43
Opened 2021-08-24 08:05 UTC by abhi-shek2000

- Migrated the whole Source Code to NULL Safety
- Used proper latest Dependencies and Corresponding Functions
- Added new Pokedex Icon for Android

2021-08-24 10:14 UTC, scitbiz requested changes

2021-08-24 10:14 UTC, scitbiz commented on lib/main.dart
> +          child: child!,
```suggestion
          child: child ?? Container(),
```

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/screens/pokedex/pokedex.dart
> +  AnimationController? _fabController;
use `late` is better in this case

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/screens/pokedex/pokedex.dart
> +class _FabMenu extends StatelessWidget {
Why not keep the widget in the old place?

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/screens/pokedex/widgets/fab_overlay_background.dart
> +        onTap: () => onPressOut,
This will not work because the callback will never be called

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/widgets/pokeball_background.dart
>      final iconSize = IconTheme.of(context).size;
```suggestion
    final iconSize = IconTheme.of(context).size ?? 0;
```
And then you can remove the `!` below

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/widgets/poke_category_card.dart
> +  final double? width;
Width must be required in this case

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/widgets/poke_category_card.dart
> +  final Color? color;
Use the default value instead

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/widgets/poke_category_card.dart
> +                  onPress!();
```suggestion
                  onPress?.();
```

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/widgets/modal.dart
> +  final String? text;
text is required in this case

2021-08-24 10:14 UTC, scitbiz commented on lib/ui/widgets/modal.dart
> +  final String? title;
title is required in this case

2021-08-24 10:14 UTC, scitbiz commented on lib/data/source/mappers/github_to_local_mapper.dart
> +    ..baseExp = baseExp!.parseDouble()
If you use the `!` incorrectly, the app will be crash and there is no point in applying null-safely. Please take a look at other `!` usage and adjust it correctly

2021-08-24 13:27 UTC, abhi-shek2000 commented
Thanks, I'll make the requested changes.

2021-10-05 05:05 UTC, scitbiz commented
Hi @abhi-shek2000, are you working on it?

2021-10-05 05:31 UTC, abhi-shek2000 commented
Hii Yeah, I'm working on it

2021-11-26 14:55 UTC, scitbiz commented
Hi @abhi-shek2000, since this PR has been inactive for a long time and the null-safety is an important feature so that it should be done as soon as possible. And since I'm the one who created this project in the first place, I think I should be the one to do it to make sure it will work correctly. So I'm sorry that I must close this PR. If you have another idea for the project or if you want to contribute, just create a new one. Thanks for your effort!

2021-11-26 14:55 UTC, closed without merging